
import { Geist, Geist_Mono,Outfit } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from './ConvexClientProvider';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit= Outfit({subsets: ["latin"]});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}