import { Geist, Geist_Mono, Outfit, Figtree } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Figtree({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
          {children}
          <Toaster />
        </ConvexClientProvider>

      </body>
    </html>
  );
}

